apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-api
  labels:
    app: label-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-api
  template:
    metadata:
      labels:
        app: label-api
    spec:
      containers:
        - name: label-api
          image: label-api
          ports:
            - containerPort: 8055
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"

---
apiVersion: v1
kind: Service
metadata:
  name: label-api
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376