# apiVersion: apps/v1
# kind: Deployment
# metadata:
# name: pim-bff
# labels:
#   app: pim-bff
# spec:
# replicas: 1
# selector:
#   matchLabels:
#     app: pim-bff
# template:
#   metadata:
#     labels:
#       app: pim-bff
#   spec:
#     containers:
#       - name: pim-bff
#         image: pim-bff
#         ports:
#           - containerPort: 3001
#         env:
#           - name: NODE_ENV
#             value: "development"
#           - name: endpoints.label_api
#             value: "http://test-api"