# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pim-storage-service
#   labels:
#     app: pim-storage-service
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: pim-storage-service
#   template:
#     metadata:
#       labels:
#         app: pim-storage-service
#     spec:
#       containers:
#         - name: pim-storage-service
#           image: pim-storage-service
#           ports:
#             - containerPort: 3001
#           env:
#             - name: NODE_ENV
#               value: "development"