apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-excel-api
  labels:
    app: product-excel-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-excel-api
  template:
    metadata:
      labels:
        app: product-excel-api
    spec:
      containers:
        - name: product-excel-api
          image: product-excel-api
          ports:
            - containerPort: 8015
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"