apiVersion: v1
kind: Service
metadata:
  name: couchbase-service
spec:
  selector:
    app: couchbase-rc-pod
  ports:
    - name: admin
      port: 8091
    - name: views
      port: 8092
    - name: query
      port: 8093
    - name: memcached
      port: 11210
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: couchbase-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: couchbase-rc-pod
    spec:
      containers:
      - name: sidecar-container
        image: ninjafx/cb:latest
      - name: couchbase
        image: couchbase/server:enterprise
        ports:
        - containerPort: 8091
        - containerPort: 8092
        - containerPort: 8093
        - containerPort: 11210
        env:
        - name: CLUSTER_NAME
          value: couchbase-demo
        - name: COUCHBASE_ADMINISTRATOR_PASSWORD
          value: password
        - name: COUCHBASE_ADMINISTRATOR_USERNAME
          value: Administrator
        - name: COUCHBASE_BUCKET
          value: ProductUploadExcel
        - name: COUCHBASE_BUCKET_RAMSIZE
          value: "512"
        - name: COUCHBASE_INDEX_RAM_SIZE
          value: "512"
        - name: COUCHBASE_RAM_SIZE
          value: "2048"
        - name: COUCHBASE_RBAC_NAME
          value: admin
        - name: COUCHBASE_RBAC_PASSWORD
          value: password
        - name: COUCHBASE_RBAC_USERNAME
          value: Administrator
