apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kowl
  name: kowl
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kowl
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: kowl
    spec:
      containers:
        - env:
            - name: KAFKA_BROKERS
              value: kafka-0.kafka-svc.default.svc.cluster.local:9092
          image: redpandadata/console:latest
          name: kowl
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}


---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: kowl
  name: kowl
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: kowl
status:
  loadBalancer: {}
